on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      tag:
        required: true
        type: string
      repository:
        required: true
        type: string
    secrets:
      username:
        required: true
      password:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to ${{ inputs.repository }}
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.repository }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - uses: actions/checkout@v2

      - name: Build docker image
        description: Pushes docker image to specified registry
        branding:
          icon: 'upload-cloud'
          color: 'layers'
        run: |
          docker build -t ${{ inputs.repository }}/${{ inputs.image }}:${{ inputs.tag }} --build-arg BUILD_COMMAND=build-test -f Dockerfile .

      - name: Push docker image
        description: Pushes docker ${{ inputs.repository }}/${{ inputs.image }}:${{ inputs.tag }}
        branding:
          icon: 'upload-cloud'
          color: 'purple'
        run: |
          docker push ${{ inputs.repository }}/${{ inputs.image }}:${{ inputs.tag }}
