on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      tag:
        required: true
        type: string
      repository:
        required: true
        type: string
      build-args:
        required: true
        type: string
    secrets:
      username:
        required: true
      password:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup build args
        run: | 
          echo "REF=$GITHUB_REPOSITORY" > ${{ runner.temp }}/build-args.env
          echo "${{ inputs.build-args }}" | awk NF >> ${{ runner.temp }}/build-args.envGITHUB_REPOSITORY

      - name: Login to ${{ inputs.repository }}
        uses: docker/login-action@v1
        with:
          registry: ${{ inputs.repository }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

      - uses: actions/checkout@v2

      - run: echo $(cat ${{ runner.temp }}/build-args.env | sed 's@^@--build-arg @g' | paste -s -d " ")

      - name: Build docker image
        run: |
          docker build -t ${{ inputs.repository }}/${{ inputs.image }}:${{ inputs.tag }} \
          $(cat ${{ runner.temp }}/build-args.env | sed 's@^@--build-arg @g' | paste -s -d " ") \
          -f Dockerfile .

      - name: Push docker image
        run: |
          docker push ${{ inputs.repository }}/${{ inputs.image }}:${{ inputs.tag }}
